//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenseTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Limit
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int ExpLimit { get; set; }
        public Nullable<int> AvalibleAmt { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
    }
}
